---
- hosts: web1-centos
  vars:
   package_name: httpd
   ignore_errors: true
   path: /etc/httpd/conf/httpd.conf
   port: 8085
   source: index.html
   service_name: httpd
  become: yes
  tasks: 
  - name: Installing packages {{ package_name }}
    yum:
     name: "{{ package_name }}"
     state: latest
    tags: 
    - install
  - name: Configuration Changes Listen to {{ port }}
    lineinfile:
     path: "{{ path }}"
     regexp: '^Listen 8084'
     line: Listen "{{ port }}"
    notify:
    - restart httpd
    tags:
    - config_only
    - config_change

  - name: Copying developer codes to web document root
    copy:
     src: "{{ source }}"
     dest: /var/www/html/index.html
    notify:
    - restart httpd
    tags:
    - code_change
    - config_change

  - name: Service start
    service:
     name: "{{ service_name }}"
     state: started
    tags:
    - service_change

  - name: Uninstalling packages {{ package_name }}
    yum:
     name: "{{ package_name }}"
     state: absent
    tags:
    - uninstall

  handlers:
  - name: restart httpd
    service:
     name: "{{ service_name }}"
     state: restarted


