---
- hosts: web1-centos
  become: yes
  tasks: 
  - name: Installing packages
    yum:
     name: httpd
     state: latest
    ignore_errors: true
  - name: Configuration Changes Listen 8080
    lineinfile:
     path: /etc/httpd/conf/httpd.conf
     regexp: '^Listen 80'
     line: Listen 8080
    ignore_errors: true
  - name: Copying developer codes to web document root
    copy:
     src: index.html
     dest: /var/www/html/index.html
    ignore_errors: true
  - name: Service start
    service:
     name: httpd
     state: started
    ignore_errors: true
